# Generated by Django 4.2.1 on 2023-06-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
    ]
