# Generated by Django 4.2.1 on 2023-06-03 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='user_to',
        ),
        migrations.AddField(
            model_name='connection',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='relationship_type',
            field=models.CharField(choices=[('P', 'Parent'), ('C', 'Child'), ('S', 'Spouse')], max_length=1),
        ),
    ]
