# Generated by Django 4.2.1 on 2023-06-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_connectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='relationship_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='relationship_type',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Son'), ('D', 'Daughter'), ('B', 'Sibling'), ('P', 'Spouse'), ('GF', 'Grandfather'), ('GM', 'Grandmother'), ('GS', 'Grandson'), ('GD', 'Granddaughter'), ('U', 'Uncle'), ('A', 'Aunt'), ('C', 'Cousin'), ('N', 'Nephew'), ('E', 'Niece'), ('FL', 'Father-in-law'), ('ML', 'Mother-in-law'), ('BL', 'Brother-in-law'), ('SL', 'Sister-in-law'), ('SI', 'Son-in-law'), ('DI', 'Daughter-in-law'), ('AF', 'Adoptive Father'), ('AM', 'Adoptive Mother'), ('AS', 'Adopted Son'), ('AD', 'Adopted Daughter'), ('AB', 'Adopted Sibling'), ('AGF', 'Adopted Grandfather'), ('AGM', 'Adopted Grandmother'), ('AGS', 'Adopted Grandson'), ('AGD', 'Adopted Granddaughter')], max_length=3),
        ),
    ]
