# Generated by Django 4.2.1 on 2023-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_connection_relationship_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='relationship_type',
            field=models.CharField(choices=[('FAT', 'Father'), ('MOT', 'Mother'), ('SON', 'Son'), ('DAU', 'Daughter'), ('SIB', 'Sibling'), ('SPO', 'Spouse'), ('GF', 'Grandfather'), ('GM', 'Grandmother'), ('GS', 'Grandson'), ('GD', 'Granddaughter'), ('UNC', 'Uncle'), ('AUN', 'Aunt'), ('COU', 'Cousin'), ('NEP', 'Nephew'), ('NIE', 'Niece'), ('FIL', 'Father-in-law'), ('MIL', 'Mother-in-law'), ('BIL', 'Brother-in-law'), ('SIL', 'Sister-in-law'), ('SIL', 'Son-in-law'), ('DIL', 'Daughter-in-law'), ('AFAT', 'Adoptive Father'), ('AMOT', 'Adoptive Mother'), ('ASON', 'Adopted Son'), ('ADAU', 'Adopted Daughter'), ('ASIB', 'Adopted Sibling'), ('AGF', 'Adopted Grandfather'), ('AGM', 'Adopted Grandmother'), ('AGS', 'Adopted Grandson'), ('AGD', 'Adopted Granddaughter')], max_length=4),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='PEN', max_length=3),
        ),
    ]
