# Generated by Django 4.2.1 on 2023-06-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='ender',
        ),
    ]
