# Generated by Django 4.2.1 on 2023-06-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_options_customuser_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo',
        ),
    ]
