# Generated by Django 4.2.1 on 2023-06-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='is_read',
        ),
    ]
